services:
  vectoria:
    image: pgvector/pgvector:pg17
    container_name: vectoria-db
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-vectordb}
      APP_USER_PASSWORD: ${APP_USER_PASSWORD:-changeme}
      RAG_USER_PASSWORD: ${RAG_USER_PASSWORD:-ragpassword}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - vectoria_data:/var/lib/postgresql/data
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-vectordb}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  vectoria_api:
    build: ./api
    container_name: vectoria-api
    ports:
      - "7979:7979"
    env_file: .env
    environment:
      DATABASE_URL: postgresql://rag_user:${RAG_USER_PASSWORD}@vectoria:${POSTGRES_PORT:-5432}/vectordb
      API_TOKENS: ${API_TOKENS}
    depends_on:
      - vectoria
    command: .venv/bin/python -m uvicorn app.main:app --host 0.0.0.0 --port 7979
    volumes:
          # For models for reranking
          - huggingface_cache:/app/.cache/huggingface
volumes:
  vectoria_data:
  huggingface_cache:
